name: milo
description: "Milo - Therapy & Companionship for the 55+"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_gif: ^0.0.4
  flutter_spinkit: ^5.2.0
  flutter_launcher_icons: ^0.14.3

  # State management
  provider: ^6.0.5

  # Audio & media
  flutter_sound: ^9.2.13
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.3
  audioplayers: ^5.1.0
  record: ^4.4.0


  # Storage & data management
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0

  # Networking & connectivity
  http: ^1.1.0
  dio: ^5.3.2
  connectivity_plus: ^5.0.1

  # Utilities
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  flutter_local_notifications: ^19.0.0
  share_plus: ^7.2.1
  uuid: ^3.0.7
  flutter_dotenv: ^5.1.0
  local_auth: ^2.1.7

  # Firebase packages
  firebase_core: ^2.25.4 #2.24.2
  firebase_analytics: ^10.8.0
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_auth: ^4.15.3
  firebase_crashlytics: ^3.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/milo_happy.gif
    - assets/images/empty_memories.png
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/milo_app_icon.png"
  adaptive_icon_background: "#FAF9F6" # Soft cream background matching our theme
  adaptive_icon_foreground: "assets/images/milo_app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true # Ensures icon fills the entire space on iOS
  web:
    generate: false
  image_path_android: "assets/images/milo_app_icon.png"
  image_path_ios: "assets/images/milo_app_icon.png"
  adaptive_icon_padding: false # Removes extra padding